- name: package install java
  ansible.builtin.package:
    state: present
    name: "{{pkg}}"

- name: package update
  shell: apt update

- name: package download tomcat
    ansible.builtin.get_url:
     url: "{{tmcurl}}"
     dest: /opt/

 - name: package unzip tomcat
    ansible.builtin.unarchive:
     src: "{{srctmcpkg}}"
     dest: "{{destunziptmc}}"
     remote_src: yes 

- name: download student.war
    ansible.builtin.get_url:
     url: "{{student.war}}"
     dest: "{{deststudentwar}}"


- name: start tomcat service
  shell: sh /home/ec2-user/apache-tomcat-9.0.70/bin/startup.sh