- name: pkg istall
  ansible.builtin.package:
    state: present
    name: httpd

- name: downlaod templete
  ansible.builtin.get_url:
    url: https://www.free-css.com/assets/files/free-css-templates/download/page286/avocado.zip
    dest: /opt/

- name: unzip
  ansible.builtin.unarchive:
    src: /opt/avocado.zip
    dest: /var/www/html/
    remote_src: yes

- name: restart httpd service
  shell: systeamctl restart httpd