
- name: pkg istall
  ansible: buildin.package:
      state: present
      name: httpd

- name: downlaod templete
  ansible: building.get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page286/avocado.zip
      dest: /opt

- name: unzip
  anisible.built.unarchive:
       src: /opt/avocado.zip
       dest: /var/www/html
       remote_src: yes

- name: restart httpd service
  shell: systeamctl restart httpd