pkg: java*
tmcurl: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.70/bin/apache-tomcat-9.0.70.tar.gz
srctmcpkg: /opt/apache-tomcat-9.0.70.tar.gz
destunziptmc: /home/ec2-user
studentwar: https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war
deststudentwar: /home/ec2-user/apache-tomcat-9.0.70/webapps
studentjar: https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war
#deststudentjar: /home/ec2-user/"{{T-dir}}"/lib
#tomcat_dir: nohup /home/ec2-user/"{{T-dir}}"/bin
#T_last: "{{tmcurl.split('/') | last}}"
#T_dir: "/opt/{{T-last | regex_replace('.zip','')}}"
